# Autostart - GQYOS
# 为顾清影而造

# 声音
exec-once = pipewire
exec-once = wireplumber

# 壁纸
exec-once = hyprpaper

# 状态栏
exec-once = waybar

# 通知
exec-once = mako

# 锁屏 & 空闲
exec-once = hypridle

# 剪贴板守护
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# 网络管理 applet
exec-once = nm-applet --indicator

# 蓝牙管理
exec-once = blueman-applet

# 输入法 (如需)
# exec-once = fcitx5
