# Window Rules - GQYOS

# 浮动窗口
windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = float, class:^(nm-connection-editor)$
windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = float, class:^(thunar)$, title:^(File Operation Progress)$
windowrulev2 = float, class:^(vue)$
windowrulev2 = float, title:^(Open File)$
windowrulev2 = float, title:^(Save As)$

# 透明度
windowrulev2 = opacity 0.90 0.85, class:^(kitty)$
windowrulev2 = opacity 0.90 0.85, class:^(Alacritty)$

# 特定应用规则
windowrulev2 = size 800 600, class:^(pavucontrol)$
windowrulev2 = size 800 600, class:^(nm-connection-editor)$
