//! assets_handlers — 静态资源与媒体流（自 src/web/sessions.rs 拆分）。

pub(crate) use super::*;

/// Strong validator shared by all build-embedded assets: the BUILD_ID
/// changes on any frontend edit (build.rs rerun triggers), so a 304 can
/// never pin a stale file.
pub(crate) fn build_etag() -> &'static HeaderValue {
    pub(crate) static ETAG_VALUE: std::sync::LazyLock<HeaderValue> =
        std::sync::LazyLock::new(|| {
            HeaderValue::from_str(concat!("\"", env!("GQY_BUILD_ID"), "\""))
                .expect("build id forms a valid header value")
        });
    &ETAG_VALUE
}

pub(crate) fn embedded_asset(
    headers: &HeaderMap,
    content: &'static [u8],
    content_type: &'static str,
) -> Response {
    if headers
        .get(axum::http::header::IF_NONE_MATCH)
        .is_some_and(|value| value == build_etag())
    {
        let mut response = StatusCode::NOT_MODIFIED.into_response();
        response
            .headers_mut()
            .insert(axum::http::header::ETAG, build_etag().clone());
        return response;
    }
    let mut response = finish_asset_response(content.into_response(), content_type);
    response
        .headers_mut()
        .insert(axum::http::header::ETAG, build_etag().clone());
    response
}

pub(crate) async fn index_asset(headers: HeaderMap) -> Response {
    // Version the asset references so browsers and intermediaries can never
    // serve a stale app.js/styles.css after an upgrade.
    pub(crate) static VERSIONED_INDEX: std::sync::LazyLock<String> =
        std::sync::LazyLock::new(|| {
            INDEX_HTML
                .replace(
                    "href=\"/styles.css\"",
                    concat!("href=\"/styles.css?v=", env!("GQY_BUILD_ID"), "\""),
                )
                .replace(
                    "src=\"/app.js\"",
                    concat!("src=\"/app.js?v=", env!("GQY_BUILD_ID"), "\""),
                )
                .replace(
                    "href=\"/vendor/katex/katex.min.css\"",
                    concat!(
                        "href=\"/vendor/katex/katex.min.css?v=",
                        env!("GQY_BUILD_ID"),
                        "\""
                    ),
                )
                .replace(
                    "src=\"/vendor/katex/katex.min.js\"",
                    concat!(
                        "src=\"/vendor/katex/katex.min.js?v=",
                        env!("GQY_BUILD_ID"),
                        "\""
                    ),
                )
        });
    embedded_asset(
        &headers,
        VERSIONED_INDEX.as_bytes(),
        "text/html; charset=utf-8",
    )
}

pub(crate) async fn styles_asset(headers: HeaderMap) -> Response {
    embedded_asset(&headers, STYLES_CSS.as_bytes(), "text/css; charset=utf-8")
}

/// Optional MD3 token override generated by matugen from the wallpaper.
/// Read from disk on every request (the file is tiny and regenerated at any
/// time); 404 when absent so the WebUI falls back to the built-in palette.
pub(crate) async fn theme_css(State(state): State<DaemonState>) -> Response {
    let path = state.paths.config_dir.join("webui-theme.css");
    match tokio::fs::read(&path).await {
        Ok(bytes) => finish_asset_response(bytes.into_response(), "text/css; charset=utf-8"),
        Err(_) => StatusCode::NOT_FOUND.into_response(),
    }
}

pub(crate) async fn app_asset(headers: HeaderMap) -> Response {
    embedded_asset(
        &headers,
        APP_JS.as_bytes(),
        "application/javascript; charset=utf-8",
    )
}

pub(crate) async fn logo_asset(headers: HeaderMap) -> Response {
    embedded_asset(&headers, GQY_LOGO, "image/png")
}

// PWA 清单（渐进式 Web 应用安装提示）。application/manifest+json 使
// iOS/Android/桌面浏览器可把 WebUI「添加到主屏幕」，成为全平台瘦客户端。
pub(crate) async fn manifest_asset(headers: HeaderMap) -> Response {
    embedded_asset(
        &headers,
        PWA_MANIFEST.as_bytes(),
        "application/manifest+json; charset=utf-8",
    )
}

// iOS/iPadOS 添加到主屏幕所需的高清图标（复用内嵌 GQY 图标）。
pub(crate) async fn apple_touch_icon_asset(headers: HeaderMap) -> Response {
    embedded_asset(&headers, GQY_LOGO, "image/png")
}

#[derive(Deserialize)]
pub(crate) struct MediaQuery {
    path: String,
}

/// 视频扩展名 → MIME。清单外一律拒绝:这个端点只做媒体流,
/// 不做通用文件下载器(尽管登录态本就有 read_file 同级能力)。
pub(crate) fn media_mime(path: &std::path::Path) -> Option<&'static str> {
    match path
        .extension()
        .and_then(|ext| ext.to_str())?
        .to_ascii_lowercase()
        .as_str()
    {
        "mp4" | "m4v" => Some("video/mp4"),
        "webm" => Some("video/webm"),
        "mov" => Some("video/quicktime"),
        "mkv" => Some("video/x-matroska"),
        "ogv" | "ogg" => Some("video/ogg"),
        "mp3" => Some("audio/mpeg"),
        "flac" => Some("audio/flac"),
        "wav" => Some("audio/wav"),
        "m4a" => Some("audio/mp4"),
        "opus" => Some("audio/ogg"),
        _ => None,
    }
}

/// 解析 `Range: bytes=start-end`(单段)。返回 (start, inclusive_end)。
pub(crate) fn parse_byte_range(value: &str, total: u64) -> Option<(u64, u64)> {
    let spec = value
        .trim()
        .strip_prefix("bytes=")?
        .split(',')
        .next()?
        .trim();
    let (start, end) = spec.split_once('-')?;
    if start.is_empty() {
        // 后缀形式 bytes=-N:最后 N 字节
        let suffix: u64 = end.parse().ok()?;
        if suffix == 0 || total == 0 {
            return None;
        }
        return Some((total.saturating_sub(suffix), total - 1));
    }
    let start: u64 = start.parse().ok()?;
    let end: u64 = if end.is_empty() {
        total.saturating_sub(1)
    } else {
        end.parse().ok()?
    };
    (start <= end && start < total).then(|| (start, end.min(total.saturating_sub(1))))
}

/// 本地媒体流:登录态可播放本机音视频文件,带 HTTP Range(拖进度条)。
pub(crate) async fn media_stream(
    State(state): State<DaemonState>,
    headers: HeaderMap,
    Query(query): Query<MediaQuery>,
) -> std::result::Result<Response, ApiError> {
    require_auth(&headers, &state)?;
    let raw = if let Some(rest) = query.path.strip_prefix("~/") {
        let home = std::env::var_os("HOME")
            .ok_or_else(|| ApiError::new(StatusCode::NOT_FOUND, "media not found"))?;
        std::path::Path::new(&home).join(rest)
    } else {
        std::path::PathBuf::from(&query.path)
    };
    let path = tokio::fs::canonicalize(&raw)
        .await
        .map_err(|_| ApiError::new(StatusCode::NOT_FOUND, "media not found"))?;
    let mime = media_mime(&path)
        .ok_or_else(|| ApiError::new(StatusCode::NOT_FOUND, "unsupported media type"))?;
    let metadata = tokio::fs::metadata(&path)
        .await
        .map_err(|_| ApiError::new(StatusCode::NOT_FOUND, "media not found"))?;
    if !metadata.is_file() {
        return Err(ApiError::new(StatusCode::NOT_FOUND, "media not found"));
    }
    let total = metadata.len();
    let range = headers
        .get(axum::http::header::RANGE)
        .and_then(|value| value.to_str().ok())
        .map(|value| parse_byte_range(value, total));
    let mut file = tokio::fs::File::open(&path)
        .await
        .map_err(|_| ApiError::new(StatusCode::NOT_FOUND, "media not found"))?;

    let (status, start, end) = match range {
        None => (StatusCode::OK, 0, total.saturating_sub(1)),
        Some(Some((start, end))) => (StatusCode::PARTIAL_CONTENT, start, end),
        Some(None) => {
            let mut response = StatusCode::RANGE_NOT_SATISFIABLE.into_response();
            response.headers_mut().insert(
                axum::http::header::CONTENT_RANGE,
                HeaderValue::from_str(&format!("bytes */{total}")).unwrap(),
            );
            return Ok(response);
        }
    };
    let length = if total == 0 { 0 } else { end - start + 1 };
    use tokio::io::AsyncSeekExt;
    file.seek(std::io::SeekFrom::Start(start))
        .await
        .map_err(ApiError::internal)?;
    let stream = tokio_util::io::ReaderStream::new(tokio::io::AsyncReadExt::take(file, length));
    let mut response = Response::new(axum::body::Body::from_stream(stream));
    *response.status_mut() = status;
    let response_headers = response.headers_mut();
    response_headers.insert(CONTENT_TYPE, HeaderValue::from_static(mime));
    response_headers.insert(CONTENT_LENGTH, HeaderValue::from(length));
    response_headers.insert(
        axum::http::header::ACCEPT_RANGES,
        HeaderValue::from_static("bytes"),
    );
    if status == StatusCode::PARTIAL_CONTENT {
        response_headers.insert(
            axum::http::header::CONTENT_RANGE,
            HeaderValue::from_str(&format!("bytes {start}-{end}/{total}")).unwrap(),
        );
    }
    response_headers.insert(CACHE_CONTROL, HeaderValue::from_static("no-store"));
    Ok(response)
}

pub(crate) async fn katex_js_asset(headers: HeaderMap) -> Response {
    embedded_asset(
        &headers,
        KATEX_JS.as_bytes(),
        "text/javascript; charset=utf-8",
    )
}

pub(crate) async fn katex_css_asset(headers: HeaderMap) -> Response {
    embedded_asset(&headers, KATEX_CSS.as_bytes(), "text/css; charset=utf-8")
}

pub(crate) async fn katex_font_asset(headers: HeaderMap, Path(font): Path<String>) -> Response {
    match KATEX_FONTS.iter().find(|(name, _)| *name == font) {
        Some((_, bytes)) => embedded_asset(&headers, bytes, "font/woff2"),
        None => StatusCode::NOT_FOUND.into_response(),
    }
}

pub(crate) async fn wallpaper_asset(headers: HeaderMap) -> Response {
    embedded_asset(&headers, GQY_WALLPAPER, "image/png")
}
